---
- name: setup Minecraft Server
  hosts: minecraft
  become: true
  tasks:
    - name: install java
      yum:
        name: java-21-amazon-corretto
        state: present

    - name: download minecraft server jar
      get_url:
        url:  https://piston-data.mojang.com/v1/objects/e6ec2f64e6080b9b5d9b471b291c33cc7f509733/server.jar
        dest: /home/ec2-user/server.jar
        mode: '0755'

    - name: accept EULA
      copy:
        dest: /home/ec2-user/eula.txt
        content: "eula=true\n"

    - name: create systemd service
      copy:
        dest: /etc/systemd/system/minecraft.service
        content: |
          [Unit]
          Description=Minecraft Server
          After=network.target

          [Service]
          User=ec2-user
          WorkingDirectory=/home/ec2-user
          ExecStart=/usr/bin/java -Xmx1024M -Xms1024M -jar server.jar nogui
          ExecStop=/bin/kill -s SIGINT $MAINPID
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: start the Minecraft server
      systemd:
        name: minecraft
        enabled: yes
        state: started
